version: "3.9"

services:
  djangoproject1:

    image: KATHYBLOG_IMAGE
    #command: python manage.py runserver 0.0.0.0:8000
    # 先收集静态文件夹，--noinput 是直接覆盖原有的文件.然后uwsgi 启动
    command: bash -c "python manage.py collectstatic --noinput && uwsgi --ini uwsgi.ini & streamlit run streamlit/dragongame.py"
    #command: uwsgi --http :8000 --module myobject.wsgi --py-autoreload=1
    volumes:
      #把静态文件夹目录挂载出来,方便 nginx 转发
      - /opt/kathyblog/static:/static
 
    deploy:
      replicas : 1
        
    ports:
      - "6500:8000"
      - "6501:8501"
    restart: always

     # 限制容器日志的大小
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "3"

  