import os


APIKEY_OPENAI=os.environ.get('APIKEY_OPENAI')
ORGANIZATION_OPENAI = os.environ.get('ORGANIZATION_OPENAI')
APIKEY_CLAUDE=os.environ.get('APIKEY_CLAUDE')
MINIO_URL = os.environ.get('MINIO_URL')


MINIO_STORAGE_ENDPOINT=os.environ.get('MINIO_STORAGE_ENDPOINT')
MINIO_STORAGE_ACCESS_KEY = os.environ.get('MINIO_STORAGE_ACCESS_KEY')
MINIO_STORAGE_SECRET_KEY = os.environ.get('MINIO_STORAGE_SECRET_KEY')
MINIO_STORAGE_USE_HTTPS = False  # 如果使用 HTTPS, 设置为 True
MINIO_STORAGE_MEDIA_BUCKET_NAME = os.environ.get('MINIO_STORAGE_MEDIA_BUCKET_NAME')
MINIO_STORAGE_AUTO_CREATE_MEDIA_BUCKET = True
