# Generated by Django 3.2 on 2024-04-12 09:02

from django.db import migrations, models
import minio_storage.storage


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(storage=minio_storage.storage.MinioMediaStorage(), upload_to='blog/')),
            ],
        ),
    ]
