# Generated by Django 3.2 on 2024-04-12 14:46

from django.db import migrations, models
import django.db.models.deletion
import minio_storage.storage


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20240412_2043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogdetail',
            name='listid',
            field=models.OneToOneField(db_column='listid', on_delete=django.db.models.deletion.CASCADE, to='home.bloglist', verbose_name='文章列表'),
        ),
        migrations.AlterField(
            model_name='bloglist',
            name='image_url',
            field=models.ImageField(storage=minio_storage.storage.MinioMediaStorage(), upload_to='blog/', verbose_name='文章主图'),
        ),
    ]
