# Generated by Django 3.2 on 2024-04-14 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20240412_2246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloglist',
            name='abstract',
            field=models.TextField(blank=True, null=True, verbose_name='摘要'),
        ),
    ]
