name: Deploy to Alibaba Cloud ECS

on:
  # 监控的 github 分支
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
 

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    
    # Checkout the repository
    - name: Checkout
      uses: actions/checkout@v2
      
    # Set up Python environment
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
        
